scrape_configs:

  - job_name: 'store-api-pull'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets:
            - 'orders:8080'  # Container "orders"
            - 'products:8080'  # Container "products"
        labels:
          application: 'store-api'
